import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.APP_CONFIG||{};
const sb=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let signup=false,user=null,member=null,members=[],events=[],weekOffset=0,taskFilter='mine',pendingScope=null;
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const iso=d=>d.toISOString().slice(0,10), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(id){['auth','onboarding','app'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
async function bootstrap(){const {data:{session}}=await sb.auth.getSession(); if(!session){show('auth');return} user=session.user; await loadMembership();}
async function loadMembership(){const {data,error}=await sb.from('family_members').select('*').eq('user_id',user.id).maybeSingle(); if(error) return toast(error.message); if(!data){show('onboarding');return} member=data; show('app'); $('#avatar').textContent=(member.display_name||'?')[0].toUpperCase(); $('#adminNav').classList.toggle('hidden',!['owner','admin'].includes(member.role)); await refreshAll();}
async function refreshAll(){const a=await sb.from('family_members').select('*').eq('family_id',member.family_id).order('display_name'); if(a.error)return toast(a.error.message);members=a.data; const d=new Date();d.setDate(d.getDate()+weekOffset*7);const start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));const end=new Date(start);end.setDate(start.getDate()+6);const q=await sb.from('events').select('*').eq('family_id',member.family_id).gte('event_date',iso(new Date(Date.now()-86400000))).lte('event_date',iso(new Date(Date.now()+120*86400000))).eq('is_cancelled',false).order('event_date').order('start_time');if(q.error)return toast(q.error.message);events=q.data;renderToday();renderWeek();renderTasks();if(['owner','admin'].includes(member.role))renderAdmin();fillPeople();}
function person(id){return members.find(m=>m.user_id===id)}
const typeIcon=t=>({school:'🎓',transport:'🚗',appointment:'📅',care:'🏠',bedtime:'🛏️'}[t]||'📅');
function card(e){const p=person(e.assignee_id)||person(e.transport_from_id)||person(e.transport_to_id);const chips=[];if(e.transport_to_id)chips.push(`Bringt: ${esc(person(e.transport_to_id)?.display_name)}`);if(e.transport_from_id)chips.push(`Holt: ${esc(person(e.transport_from_id)?.display_name)}`);if(e.assignee_id)chips.push(`Zuständig: ${esc(person(e.assignee_id)?.display_name)}`);return `<article class="event-card" data-id="${e.id}" style="--person:${p?.color||'#999'}"><small>${typeIcon(e.event_type)} ${e.start_time?.slice(0,5)||'Ganztägig'}</small><h3>${esc(e.title)}</h3>${e.location?`<div>${esc(e.location)}</div>`:''}<div class="chips">${chips.map(x=>`<span class="chip">${x}</span>`).join('')}${(e.reminders||[]).map(x=>`<span class="chip">🔔 ${x} Min.</span>`).join('')}</div></article>`}
function renderToday(){const today=iso(new Date()),list=events.filter(e=>e.event_date===today);$('#todayList').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Heute ist nichts eingetragen.</div>';const next=list.find(e=>!e.start_time||new Date(`${e.event_date}T${e.start_time}`)>new Date())||list[0];$('#nextTask').innerHTML=next?`<small>NÄCHSTER TERMIN</small><h2>${esc(next.title)}</h2><div>${next.start_time?.slice(0,5)||'Ganztägig'} · ${esc(person(next.assignee_id)?.display_name||'noch ungeklärt')}</div>`:'<small>HEUTE</small><h2>Keine weiteren Termine</h2>';bindCards();}
function weekBounds(){const d=new Date();d.setDate(d.getDate()+weekOffset*7);const s=new Date(d);s.setDate(d.getDate()-((d.getDay()+6)%7));const e=new Date(s);e.setDate(s.getDate()+6);return[s,e]}
function renderWeek(){const[s,e]=weekBounds();$('#weekRange').textContent=`${s.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}–${e.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}`;let html='';for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1)){const day=events.filter(x=>x.event_date===iso(d));html+=`<h3>${d.toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'})}</h3>${day.length?day.map(card).join(''):'<div class="empty">Keine Termine</div>'}`}$('#weekList').innerHTML=html;bindCards();}
function renderTasks(){let list=events.filter(e=>['transport','care','bedtime'].includes(e.event_type));if(taskFilter==='mine')list=list.filter(e=>[e.assignee_id,e.transport_to_id,e.transport_from_id].includes(user.id));if(taskFilter==='open')list=list.filter(e=>!e.assignee_id&&!e.transport_to_id&&!e.transport_from_id);$('#tasksList').innerHTML=list.length?list.slice(0,50).map(e=>`<h4>${new Date(e.event_date+'T12:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</h4>${card(e)}`).join(''):'<div class="empty">Keine passenden Aufgaben.</div>';bindCards();}
function bindCards(){$$('.event-card').forEach(x=>x.onclick=()=>openEvent(events.find(e=>e.id===x.dataset.id)))}
function fillPeople(){const opts='<option value="">— ungeklärt —</option>'+members.map(m=>`<option value="${m.user_id}">${esc(m.display_name)}</option>`).join('');['assignee','transportTo','transportFrom'].forEach(id=>$('#'+id).innerHTML=opts)}
function addReminder(v=15){const n=$('#reminderTpl').content.cloneNode(true);n.querySelector('input').value=v;n.querySelector('button').onclick=e=>e.target.closest('.reminder').remove();$('#reminders').append(n)}
function openEvent(e=null){$('#eventForm').reset();$('#reminders').innerHTML='';$('#eventId').value=e?.id||'';$('#seriesId').value=e?.series_id||'';$('#eventHeading').textContent=e?'Termin bearbeiten':'Termin anlegen';$('#deleteEvent').classList.toggle('hidden',!e);$('#eventDate').value=e?.event_date||iso(new Date());$('#eventType').value=e?.event_type||'appointment';$('#eventTitle').value=e?.title||'';$('#startTime').value=e?.start_time?.slice(0,5)||'';$('#endTime').value=e?.end_time?.slice(0,5)||'';$('#allDay').value=String(e?.all_day||false);$('#location').value=e?.location||'';$('#notes').value=e?.notes||'';$('#assignee').value=e?.assignee_id||'';$('#transportTo').value=e?.transport_to_id||'';$('#transportFrom').value=e?.transport_from_id||'';(e?.reminders||[member.default_reminder_minutes||15]).forEach(addReminder);$('#recurrence').value='none';$('#recurrenceEnd').value='';$('#eventDialog').showModal()}
function payload(){return {family_id:member.family_id,event_type:$('#eventType').value,title:$('#eventTitle').value.trim(),event_date:$('#eventDate').value,start_time:$('#startTime').value||null,end_time:$('#endTime').value||null,all_day:$('#allDay').value==='true',location:$('#location').value.trim(),notes:$('#notes').value.trim(),assignee_id:$('#assignee').value||null,transport_to_id:$('#transportTo').value||null,transport_from_id:$('#transportFrom').value||null,reminders:$$('#reminders input').map(x=>Number(x.value)),created_by:user.id}}
async function saveEvent(ev){ev.preventDefault();const p=payload(),id=$('#eventId').value,series=$('#seriesId').value;if(id&&series){pendingScope=async scope=>{if(scope!=='cancel'){const {error}=await sb.rpc('update_series_scope',{p_occurrence_id:id,p_scope:scope,p_patch:p});if(error)toast(error.message);else done()}};return $('#scopeDialog').showModal()}let r;if(id)r=await sb.from('events').update({...p,created_by:undefined,updated_at:new Date().toISOString()}).eq('id',id);else if($('#recurrence').value!=='none')r=await sb.rpc('create_event_series',{p_event:p,p_recurrence:$('#recurrence').value,p_until:$('#recurrenceEnd').value||null});else r=await sb.from('events').insert(p);if(r.error)toast(r.error.message);else done()}
async function deleteEvent(){const id=$('#eventId').value,series=$('#seriesId').value;if(!confirm('Termin wirklich löschen?'))return;if(series){pendingScope=async scope=>{if(scope!=='cancel'){const {error}=await sb.rpc('delete_series_scope',{p_occurrence_id:id,p_scope:scope});if(error)toast(error.message);else done()}};return $('#scopeDialog').showModal()}const {error}=await sb.from('events').delete().eq('id',id);if(error)toast(error.message);else done()}
async function done(){$('#eventDialog').close();$('#scopeDialog').close();toast('Gespeichert');await refreshAll()}
function renderAdmin(){$('#adminContent').innerHTML=`<h2>Administration</h2><div class="admin-grid"><div class="card"><h3>Familienmitglieder</h3><div id="memberList"></div></div><div class="card"><h3>Mitglied einladen</h3><p>Die eingeladene Person braucht nur ein Konto und diesen Code. Kein Supabase-Zugriff.</p><label>E-Mail der Person<input id="inviteEmail" type="email" placeholder="oma@example.de"></label><button id="makeInvite" class="primary">Einladungscode erzeugen</button><div id="inviteResult"></div></div></div>`;$('#memberList').innerHTML=members.map(m=>`<div class="member"><span class="dot" style="background:${m.color}"></span><main><b>${esc(m.display_name)}</b><small>${m.role}</small></main>${member.role==='owner'||(member.role==='admin'&&m.role==='member')?`<button data-edit-member="${m.user_id}">Bearbeiten</button>`:''}</div>`).join('');$('#makeInvite').onclick=makeInvite;$$('[data-edit-member]').forEach(b=>b.onclick=()=>editMember(b.dataset.editMember))}
async function makeInvite(){const email=$('#inviteEmail').value.trim();if(!email)return toast('Bitte E-Mail eingeben');const {data,error}=await sb.rpc('create_family_invitation',{p_email:email});if(error)return toast(error.message);$('#inviteResult').innerHTML=`<p>Code für ${esc(email)}:</p><div class="code">${esc(data)}</div><p class="small">Die Person öffnet die App, registriert sich und tippt auf „Mit Einladungscode beitreten“.</p>`}
function editMember(id){const m=person(id);$('#settingsHeading').textContent='Mitglied bearbeiten';$('#settingsContent').innerHTML=`<label>Name<input id="mName" value="${esc(m.display_name)}"></label><label>Farbe<input id="mColor" type="color" value="${m.color}"></label><label>Rolle<select id="mRole"><option value="member">Mitglied</option><option value="admin">Administrator</option>${member.role==='owner'?'<option value="owner">Eigentümer</option>':''}</select></label><button id="saveMember" class="primary">Speichern</button>`;$('#mRole').value=m.role;$('#saveMember').onclick=async()=>{const {error}=await sb.rpc('admin_update_member',{p_user_id:id,p_role:$('#mRole').value,p_color:$('#mColor').value,p_display_name:$('#mName').value.trim()});if(error)toast(error.message);else{$('#settingsDialog').close();await refreshAll()}};$('#settingsDialog').showModal()}
async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window))return toast('Push wird auf diesem Gerät nicht unterstützt');if(!cfg.VAPID_PUBLIC_KEY)return toast('Push ist vom Eigentümer noch nicht fertig eingerichtet');const reg=await navigator.serviceWorker.register('./service-worker.js');const perm=await Notification.requestPermission();if(perm!=='granted')return toast('Benachrichtigungen wurden nicht erlaubt');const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlB64(cfg.VAPID_PUBLIC_KEY)});const {error}=await sb.from('push_subscriptions').upsert({user_id:user.id,endpoint:sub.endpoint,subscription:sub.toJSON(),user_agent:navigator.userAgent},{onConflict:'endpoint'});toast(error?error.message:'Push ist aktiviert')}
function urlB64(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b);return Uint8Array.from([...r].map(c=>c.charCodeAt(0)))}
function openSettings(action){$('#settingsDialog').showModal();if(action==='notifications'){$('#settingsHeading').textContent='Benachrichtigungen';$('#settingsContent').innerHTML=`<p>Erinnerungen werden entsprechend der Minutenangaben am Termin versendet.</p><label>Standard-Vorlauf in Minuten<input id="defaultReminder" type="number" min="0" value="${member.default_reminder_minutes}"></label><label><input id="notifyAssignments" type="checkbox" ${member.notify_assignments?'checked':''}> Neue eigene Aufgaben melden</label><label><input id="notifyChanges" type="checkbox" ${member.notify_changes?'checked':''}> Änderungen melden</label><button id="saveNotify" class="primary">Einstellungen speichern</button><button id="enablePush" class="secondary" style="width:100%;margin-top:10px">Push auf diesem Gerät aktivieren</button>`;$('#saveNotify').onclick=async()=>{const u={default_reminder_minutes:Number($('#defaultReminder').value),notify_assignments:$('#notifyAssignments').checked,notify_changes:$('#notifyChanges').checked};const {error}=await sb.from('family_members').update(u).eq('family_id',member.family_id).eq('user_id',user.id);if(error)toast(error.message);else{member={...member,...u};toast('Gespeichert')}};$('#enablePush').onclick=enablePush}else if(action==='profile'){$('#settingsHeading').textContent='Mein Profil';$('#settingsContent').innerHTML=`<label>Name<input id="profileName" value="${esc(member.display_name)}"></label><label>Farbe<input id="profileColor" type="color" value="${member.color}"></label><button id="saveProfile" class="primary">Speichern</button>`;$('#saveProfile').onclick=async()=>{const u={display_name:$('#profileName').value.trim(),color:$('#profileColor').value};const {error}=await sb.from('family_members').update(u).eq('family_id',member.family_id).eq('user_id',user.id);if(error)toast(error.message);else{$('#settingsDialog').close();await loadMembership()}}}else{toast('Auf dem iPhone: Safari → Teilen → Zum Home-Bildschirm');$('#settingsDialog').close()}}
$('#toggleSignup').onclick=()=>{signup=!signup;$('#nameWrap').classList.toggle('hidden',!signup);$('#authSubmit').textContent=signup?'Konto anlegen':'Anmelden';$('#toggleSignup').textContent=signup?'Schon ein Konto? Anmelden':'Neues Konto anlegen'};
$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#email').value,password=$('#password').value;const r=signup?await sb.auth.signUp({email,password,options:{data:{display_name:$('#displayName').value.trim()}}}):await sb.auth.signInWithPassword({email,password});if(r.error)return toast(r.error.message);$('#authInfo').textContent=signup&&!r.data.session?'Bitte E-Mail bestätigen und danach anmelden.':'';if(r.data.session){user=r.data.user;await loadMembership()}};
$('#createFamilyChoice').onclick=()=>{$('#createFamilyBox').classList.remove('hidden');$('#joinFamilyBox').classList.add('hidden')};$('#joinFamilyChoice').onclick=()=>{$('#joinFamilyBox').classList.remove('hidden');$('#createFamilyBox').classList.add('hidden')};
$('#createFamilyBtn').onclick=async()=>{const {error}=await sb.rpc('create_family',{p_name:$('#familyName').value.trim()});if(error)toast(error.message);else await loadMembership()};
$('#joinFamilyBtn').onclick=async()=>{const {error}=await sb.rpc('join_family',{p_code:$('#inviteCode').value.trim()});if(error)toast(error.message);else await loadMembership()};
$('#logout').onclick=$('#onboardingLogout').onclick=async()=>{await sb.auth.signOut();location.reload()};
$$('nav [data-view]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active');$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').textContent=b.querySelector('small')?.textContent||'Kalender'});
$('#add').onclick=()=>openEvent();$('#refresh').onclick=refreshAll;$('#prevWeek').onclick=()=>{weekOffset--;renderWeek()};$('#nextWeek').onclick=()=>{weekOffset++;renderWeek()};$('#addReminder').onclick=()=>addReminder();$('#eventForm').onsubmit=saveEvent;$('#deleteEvent').onclick=deleteEvent;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('#scopeDialog [data-scope]').forEach(b=>b.onclick=()=>{const f=pendingScope;pendingScope=null;f?.(b.dataset.scope)});$$('[data-filter]').forEach(b=>b.onclick=()=>{taskFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});$$('#moreView [data-action]').forEach(b=>b.onclick=()=>openSettings(b.dataset.action));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});sb.auth.onAuthStateChange((_e,s)=>{if(!s)show('auth')});bootstrap();
