window.APP_CONFIG = {
  SUPABASE_URL: "HIER_DEINE_SUPABASE_URL_EINTRAGEN",
  SUPABASE_ANON_KEY: "HIER_DEINEN_SUPABASE_ANON_KEY_EINTRAGEN",
  VAPID_PUBLIC_KEY: "",
  APP_NAME: "Leonhards Familienkalender"
};
