window.APP_CONFIG = {
  SUPABASE_URL: "HIER_DEINE_SUPABASE_URL_EINTRAGEN",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZianZsa2d2c2F0bmpydG9pZ3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNDI4NzAsImV4cCI6MjEwMDcxODg3MH0.GQ-Py7Sy1dnb1wSCksYTpdeGgJbNusNuZEnaQUrA6mk",
  VAPID_PUBLIC_KEY: "",
  APP_NAME: "Leonhards Familienkalender"
};
