import test from 'node:test';
import assert from 'node:assert/strict';
import {EventCache,sessionRead} from '../event-cache.js';
test('cached days and overlapping weeks require only missing ranges',async()=>{const c=new EventCache(),calls=[];const fetch=async(a,b)=>{calls.push([a,b]);return [{id:a,event_date:a,end_date:b}];};await c.load([['2026-10-06','2026-11-05']],fetch);await c.load([['2026-10-12','2026-10-18']],fetch);assert.equal(calls.length,1);await c.load([['2026-11-02','2026-11-08']],fetch);assert.deepEqual(calls.at(-1),['2026-11-06','2026-11-08']);await c.load([['2026-10-05','2026-10-11']],fetch);assert.deepEqual(calls.at(-1),['2026-10-05','2026-10-05']);});
test('failed range is not cached and concurrent loads share completed coverage',async()=>{const c=new EventCache();await assert.rejects(c.load([['2026-10-06','2026-10-06']],async()=>{throw Error('offline');}));assert.equal(c.ranges.length,0);let n=0;await Promise.all([c.load([['2026-10-06','2026-10-12']],async()=>{n++;return [];}),c.load([['2026-10-08','2026-10-10']],async()=>{n++;return [];})]);assert.equal(n,1);});
test('overlapping multi-day events deduplicate and refreshed rows replace old values',async()=>{const c=new EventCache();c.remember('2026-10-06','2026-10-08',[{id:'night',event_date:'2026-10-05',end_date:'2026-10-09',title:'Old'}]);c.remember('2026-10-09','2026-10-09',[{id:'night',event_date:'2026-10-05',end_date:'2026-10-09',title:'New'}]);assert.equal(c.rows.size,1);assert.equal(c.rows.get('night').title,'New');assert.deepEqual(c.ranges,[['2026-10-06','2026-10-09']]);});
test('permission error renews session once and retries, network failures never log out',async()=>{let renew=0,reads=0;const sb={auth:{getSession:async()=>({data:{session:{user:{id:'u'}}}}),refreshSession:async()=>{renew++;return {data:{session:{user:{id:'u'}}}};}}};assert.equal(await sessionRead(sb,'u',async()=>{reads++;if(reads===1)throw {code:'42501'};return 'ok';}),'ok');assert.equal(renew,1);await assert.rejects(sessionRead(sb,'u',async()=>{throw Error('network');}),/network/);assert.equal(renew,1);});
test('missing or different account cannot issue a data read',async()=>{for(const session of [null,{user:{id:'other'}}]){let calls=0;await assert.rejects(sessionRead({auth:{getSession:async()=>({data:{session}})}},'u',()=>{calls++;}),/erneut anmelden/);assert.equal(calls,0);}});
test('permanent permission failure retries only once and invalid refresh requires login',async()=>{let n=0;const sb={auth:{getSession:async()=>({data:{session:{user:{id:'u'}}}}),refreshSession:async()=>({data:{session:{user:{id:'u'}}}})}};await assert.rejects(sessionRead(sb,'u',async()=>{n++;throw {code:'42501'};}));assert.equal(n,2);sb.auth.refreshSession=async()=>({error:Error('invalid')});await assert.rejects(sessionRead(sb,'u',async()=>{throw {code:'42501'};}),/erneut anmelden/);});
