-- Isolated API/permission smoke test. No real family, email or device touched.
begin;
do $$
declare f uuid:=gen_random_uuid(); owner_id uuid:=gen_random_uuid(); member_id uuid:=gen_random_uuid(); outsider_id uuid:=gen_random_uuid(); other_f uuid:=gen_random_uuid();
 owner_p uuid; member_p uuid; leo_p uuid; owner_c uuid; member_c uuid; leo_c uuid; eid uuid; leo_event uuid; data jsonb; stamp text; bad boolean; n int:=0; code text:=replace(gen_random_uuid()::text,'-','');
begin
 insert into auth.users(id,email,email_confirmed_at) values(owner_id,'v170-owner-'||owner_id||'@example.invalid',now()),(member_id,'v170-member-'||member_id||'@example.invalid',now()),(outsider_id,'v170-outside-'||outsider_id||'@example.invalid',now());
 insert into public.families(id,name) values(f,'Isolated 1.7 check'),(other_f,'Isolated outsider');
 insert into public.family_members(family_id,user_id,display_name,role) values(f,owner_id,'Owner','owner'),(other_f,outsider_id,'Outsider','owner');
 insert into public.family_people(family_id,display_name,linked_user_id,include_in_all_tasks) values(f,'Owner',owner_id,true) returning id into owner_p;
 insert into public.family_people(family_id,display_name) values(f,'Member') returning id into member_p;
 insert into public.family_people(family_id,display_name) values(f,'Child') returning id into leo_p;
 insert into public.calendars(family_id,person_id,display_name) values(f,owner_p,'Owner') returning id into owner_c;
 insert into public.calendars(family_id,person_id,display_name) values(f,member_p,'Member') returning id into member_c;
 insert into public.calendars(family_id,person_id,display_name,allow_family_create) values(f,leo_p,'Child',true) returning id into leo_c;
 insert into public.family_invitations(family_id,email,code,created_by,calendar_id) values(f,'v170-member-'||member_id||'@example.invalid',upper(code),owner_id,member_c);
 perform set_config('request.jwt.claim.sub',member_id::text,true);set local role authenticated;
 perform public.join_family(code);
 if (select linked_user_id from public.family_people where id=member_p) is distinct from member_id then raise exception 'Invite identity lost';end if;n:=n+1;
 if (select count(*) from public.calendars)<>3 then raise exception 'Duplicate calendar or RLS leak';end if;n:=n+1;
 if (select include_in_all_tasks from public.family_people where id=member_p) then raise exception 'Link silently joined All';end if;n:=n+1;
 data:=jsonb_build_object('family_id',f,'calendar_ids',jsonb_build_array(member_c),'title','One minute','event_type','appointment','event_date','2030-01-01','end_date','2030-01-01','start_time','10:00','end_time','10:01','reminders',jsonb_build_array(15),'assignments','[]'::jsonb);
 eid:=public.save_calendar_event_v170(data);if eid is null then raise exception 'Own save failed';end if;n:=n+1;
 bad:=false;begin perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(owner_c)));exception when others then bad:=true;end;if not bad then raise exception 'Other calendar accepted';end if;n:=n+1;
 bad:=false;begin perform public.save_calendar_event_v170(data||jsonb_build_object('end_time',null));exception when others then bad:=true;end;if not bad then raise exception 'Missing end accepted';end if;n:=n+1;
 bad:=false;begin perform public.save_calendar_event_v170(data||jsonb_build_object('end_time','10:00'));exception when others then bad:=true;end;if not bad then raise exception 'Zero duration accepted';end if;n:=n+1;
 bad:=false;begin perform public.save_calendar_event(data);exception when others then bad:=true;end;if not bad then raise exception 'Old writer accepted';end if;n:=n+1;
 bad:=false;begin update public.events set title='Bypass' where id=eid;exception when insufficient_privilege then bad:=true;end;if not bad then raise exception 'Direct write accepted';end if;n:=n+1;
 leo_event:=public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c)));
 select updated_at::text into stamp from public.events where id=leo_event;
 perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c),'expected_updated_at',stamp,'title','Changed'),leo_event);n:=n+1;
 bad:=false;begin perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c),'expected_updated_at',stamp),leo_event);exception when others then bad:=true;end;if not bad then raise exception 'Stale edit accepted';end if;n:=n+1;
 perform public.calendar_cancel_v170(eid,true);perform public.calendar_cancel_v170(eid,false);n:=n+1;
 bad:=false;begin perform public.manage_calendar(p_name:='Illegal');exception when others then bad:=true;end;if not bad then raise exception 'Member manages calendars';end if;n:=n+1;
 reset role;perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 eid:=public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c)));n:=n+1;
 reset role;perform set_config('request.jwt.claim.sub',member_id::text,true);set local role authenticated;
 if private.calendar_can_edit(eid) then raise exception 'Other child event editable';end if;n:=n+1;
 perform public.calendar_self_assign(eid,'assignee',true);
 if not exists(select 1 from public.event_assignments where event_id=eid and person_id=member_p and role='assignee') then raise exception 'Self task failed';end if;n:=n+1;
 perform public.calendar_self_assign(eid,'assignee',false);
 if exists(select 1 from public.event_assignments where event_id=eid and person_id=member_p and role='assignee') then raise exception 'Task release failed';end if;n:=n+1;
 bad:=false;begin perform public.calendar_self_assign(eid,'to',true);exception when others then bad:=true;end;if not bad then raise exception 'Retired to accepted';end if;n:=n+1;
 bad:=false;begin perform public.calendar_self_assign(eid,'from',true);exception when others then bad:=true;end;if not bad then raise exception 'Retired from accepted';end if;n:=n+1;
 bad:=false;begin perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(member_c),'assignments',jsonb_build_array(jsonb_build_object('role','to','person_id',member_p))));exception when others then bad:=true;end;if not bad then raise exception 'Retired role save accepted';end if;n:=n+1;
 reset role;perform set_config('request.jwt.claim.sub',outsider_id::text,true);set local role authenticated;
 if exists(select 1 from public.events where family_id=f) or exists(select 1 from public.calendars where family_id=f) then raise exception 'Cross-family RLS leak';end if;n:=n+1;
 reset role;perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 eid:=public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c)),null,'single','daily','2030-01-03');
 select updated_at::text into stamp from public.events where id=eid;
 perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c),'expected_updated_at',stamp,'title','Single update'),eid,'single');n:=n+1;
 select updated_at::text into stamp from public.events where id=eid;
 perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c),'expected_updated_at',stamp,'title','Following update'),eid,'following');n:=n+1;
 select updated_at::text into stamp from public.events where id=eid;
 perform public.save_calendar_event_v170(data||jsonb_build_object('calendar_ids',jsonb_build_array(leo_c),'expected_updated_at',stamp,'title','Whole series update'),eid,'series');n:=n+1;
 reset role;
 insert into public.push_subscriptions(user_id,endpoint,subscription) values(owner_id,'https://web.push.apple.com/v175-test-'||owner_id,'{}'),(member_id,'https://web.push.apple.com/v175-test-'||member_id,'{}');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
 eid:=public.save_calendar_event_v170(data||jsonb_build_object('event_type','bedtime','calendar_ids',jsonb_build_array(owner_c),'assignee_all',true));
 reset role;
 if (select count(*) from private.push_eligible('2030-01-01 08:45:00+00') where event_id=eid and user_id=owner_id)<>1 then raise exception 'All bedtime owner not notified exactly once';end if;n:=n+1;
 if exists(select 1 from private.push_eligible('2030-01-01 08:45:00+00') where event_id=eid and user_id=member_id) then raise exception 'Non-group member got All reminder';end if;n:=n+1;
 select updated_at::text into stamp from public.events where id=eid;
 set local role authenticated;
 perform public.save_calendar_event_v170(data||jsonb_build_object('event_type','bedtime','calendar_ids',jsonb_build_array(owner_c),'assignee_all',false,'assignments',jsonb_build_array(jsonb_build_object('role','assignee','person_id',member_p)),'expected_updated_at',stamp),eid);
 reset role;
 if exists(select 1 from private.push_eligible('2030-01-01 08:45:00+00') where event_id=eid and user_id=owner_id) then raise exception 'Calendar-only bedtime owner notified';end if;n:=n+1;
 if (select count(*) from private.push_eligible('2030-01-01 08:45:00+00') where event_id=eid and user_id=member_id and roles='Zuständig')<>1 then raise exception 'Chosen bedtime member not notified exactly once';end if;n:=n+1;
 if has_function_privilege('anon','public.manage_calendar(uuid,text,text,integer,boolean,boolean)','execute') or has_function_privilege('authenticated','public.prepare_family_access_link_v170(uuid,text,text,uuid,uuid)','execute') then raise exception 'Privileged RPC exposed';end if;n:=n+1;
 raise notice '% isolated 1.7 checks passed',n;
end $$;
-- Force the same deferred calendar checks a real COMMIT invokes.
set constraints all immediate;
rollback;
